run:
    npx parcel --open

build:
    rm -rf dist
    just generate-api-client
    npx parcel build

setup:
    npm install

lint *args:
    npx eslint {{ args }} .
    npx tsc

generate-api-client *args:
    #!/bin/bash
    cd ../backend
    just generate-api-spec
    cd ../frontend
    rm -rf src/api
    npx openapi-generator-cli generate \
        --input-spec ../backend/openapi.json \
        --generator-name typescript-fetch \
        --output ./src/api \
        --additional-properties \
    "supportsES6=true,\
    withInterfaces=true,\
    enumNameSuffix=,\
    enumPropertyNaming=UPPERCASE,\
    modelPropertyNaming=camelCase,\
    typescriptThreePlus=true,\
    stringEnums=true\
    " {{ args }}

format:
    just lint --fix
