run:
    poetry run python ./main.py run

run-reset: seed run

createdb:
    poetry run python ./main.py createdb

dropdb:
    poetry run python ./main.py dropdb

seed: resetdb
    poetry run python ./main.py seed

resetdb: dropdb createdb

setup:
    poetry lock --no-update
    poetry install

lint:
    poetry run black app --check
    poetry run isort \
        --skip __init__.py \
        --check-only app
    poetry run flake8 \
        --exclude __init__.py,.venv

format:
    # remove unused imports
    poetry run autoflake \
        --remove-all-unused-imports \
        --recursive \
        --in-place app \
        --exclude=__init__.py,.venv
    poetry run black app
    poetry run isort app \
        --skip __init__.py

generate-api-spec:
    poetry run python ./main.py generate-api-spec


# Watch for something
# E.g. `just watch lint` or `just watch test`
watch *args:
    watchexec -e py --restart --clear clear 'just {{ args }}'
