run:
    poetry run python ./main.py run

run-reset: seed run

createdb:
    poetry run python ./main.py createdb

dropdb:
    poetry run python ./main.py dropdb

seed: resetdb
    poetry run python ./main.py seed

resetdb: dropdb createdb

setup:
    poetry lock --no-update
    poetry install

lint:
    poetry run ruff check ./app --output-format=full
    poetry run ruff format ./app --diff

format:
    poetry run ruff check --fix ./app
    poetry run ruff format ./app

generate-api-spec:
    poetry run python ./main.py generate-api-spec


# Watch for something
# E.g. `just watch lint` or `just watch test`
watch *args:
    watchexec -e py --restart --clear 'just {{ args }}'
