run:
    uv run ./main.py run

run-reset: seed run

createdb:
    uv run ./main.py createdb

dropdb:
    uv run ./main.py dropdb

seed: resetdb
    uv run ./main.py seed

resetdb: dropdb createdb

setup:
    uv sync

lint:
    uv run ruff check ./app --output-format=full
    uv run ruff format ./app --diff

format:
    uv run ruff check --fix ./app
    uv run ruff format ./app

generate-api-spec:
    uv run ./main.py generate-api-spec


# Watch for something
# E.g. `just watch lint` or `just watch test`
watch *args:
    watchexec -e py --restart --clear clear 'just {{ args }}'
